[WIP] Implement for App Alert
revamp-with-react/ungit-react pull request #5
Opened 2017-06-05 15:50 UTC by AllenFang

Commit some useful and important part for reviewing.

**Target**: implement the alert area on `component/app/app.js`.

Please also review this PR by each commits

2017-06-05 15:56 UTC, AllenFang commented
Currently, we can get some basic data via this PR

<img width="373" alt="2017-06-05 11 54 58" src="https://cloud.githubusercontent.com/assets/5351390/26791719/8cc64328-4a4a-11e7-9c6a-a10d2012b99a.png">

2017-06-10 06:40 UTC, AllenFang commented
@CYBAI please have a look on it, this PR have following tasks done, and you can merge it due to it will be easy and helpful for the development of your part.

* `redux-thunk`
* A basic state tree(check `src-react/store.js`) and reducers implementation(check `src-react/reducers`)
* `path` container implementation, now we have an essential entry point for path page

I'm going to open another two PR 

One is for implement the components(`AlertArea`) event, because this PR only have the view(presentation) but I doesn't implement the events(click etc.) yet.

The other is for the testing.

2017-06-11 11:23 UTC, CYBAI requested changes

2017-06-11 11:23 UTC, CYBAI commented on src-react/actions/ungit-config.js
> +function receiveUgitConfig(ungitConfig) {
I think it's typo in the function name?

`receiveUgitConfig` => receiveU`n`gitConfig

2017-06-11 11:23 UTC, CYBAI commented on src-react/containers/path.js
> +import AlerArea from 'components/alert-area';
typo here for Aler`t`Area

2017-06-11 11:23 UTC, CYBAI commented on src-react/actions/bootstrap.js
> +    dispatch(pending(4));
Just want to make my understanding much clearer.
I think the usage of `pending` is to know how many APIs don't finish yet.

If my understanding is correct, according to this `bootstrap` action, there're three `fetch` action, why do you use `4` here?

2017-06-11 13:07 UTC, AllenFang commented on src-react/actions/bootstrap.js
> +    dispatch(pending(4));
Due to ungitconfig action will also fetch userconfig, but after I check the code, there's a condition  to decide if fetching userconfig or not, so I think I need to move a pending call into ungitconfig

It's fixed

2017-06-11 13:07 UTC, AllenFang commented on src-react/containers/path.js
> +import AlerArea from 'components/alert-area';
fixed

2017-06-11 13:07 UTC, AllenFang commented on src-react/actions/ungit-config.js
> +function receiveUgitConfig(ungitConfig) {
fixed

2017-06-11 13:21 UTC, CYBAI approved these changes

2017-06-11 13:23 UTC, merged