Fix type error cannot read property async
revamp-with-react/ungit-react pull request #9
Opened 2017-06-27 15:08 UTC by AllenFang

Try to fix https://github.com/revamp-with-react/ungit-react/pull/7#issuecomment-310895441

2017-06-27 15:21 UTC, AllenFang commented
@CYBAI, please review, seems like Travis was pass now.

2017-06-27 15:28 UTC, CYBAI requested changes
Thanks for your great work.
The fix looks good to me.
I think only the requiring path of utils in tests is the last part need updating.

2017-06-27 15:28 UTC, CYBAI commented on src-react/__tests__/middlewares/redux-api/ungit-config.test.js
> +import { FETCH_HEADER } from '../../utils/constants';
Can we require util without dots?
ex. `import { FETCH_HEADER } from 'utils/constants'`

2017-06-28 15:50 UTC, AllenFang commented on src-react/__tests__/middlewares/redux-api/ungit-config.test.js
> +import { FETCH_HEADER } from '../../utils/constants';
done

2017-06-29 15:14 UTC, CYBAI approved these changes

2017-07-11 13:11 UTC, AllenFang commented
@CYBAI, I revert the lastest commit about resolving `'../../utils/constants'`, Because for fixing this issue, I add following in `package.json`:

```js
"moduleDirectories": [ 'node_modules', 'src-react/__test__' ]
```

But it most like cause a import naming conflict for `app`, for example, 

You can imagine this [line](https://github.com/revamp-with-react/ungit-react/blob/phase-1/src-react/__tests__/reducers/app.js#L4) and guess what module will be imported?!.

I try to avoid it bug but still fails, and also I think it's not very important that must handle this relative path in testing code, 

Please give some useful solution if you have, thanks

2017-07-11 13:12 UTC, merged

2017-07-11 15:45 UTC, CYBAI commented
@AllenFang Okay, if I have better solution for this, I'll discuss with you.